// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Articles          string
	ClickbaitKeywords string
	Labels            string
	Users             string
}{
	Articles:          "articles",
	ClickbaitKeywords: "clickbait_keywords",
	Labels:            "labels",
	Users:             "users",
}
