// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Headlines", testHeadlines)
	t.Run("Labels", testLabels)
	t.Run("Users", testUsers)
}

func TestDelete(t *testing.T) {
	t.Run("Headlines", testHeadlinesDelete)
	t.Run("Labels", testLabelsDelete)
	t.Run("Users", testUsersDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Headlines", testHeadlinesQueryDeleteAll)
	t.Run("Labels", testLabelsQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Headlines", testHeadlinesSliceDeleteAll)
	t.Run("Labels", testLabelsSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Headlines", testHeadlinesExists)
	t.Run("Labels", testLabelsExists)
	t.Run("Users", testUsersExists)
}

func TestFind(t *testing.T) {
	t.Run("Headlines", testHeadlinesFind)
	t.Run("Labels", testLabelsFind)
	t.Run("Users", testUsersFind)
}

func TestBind(t *testing.T) {
	t.Run("Headlines", testHeadlinesBind)
	t.Run("Labels", testLabelsBind)
	t.Run("Users", testUsersBind)
}

func TestOne(t *testing.T) {
	t.Run("Headlines", testHeadlinesOne)
	t.Run("Labels", testLabelsOne)
	t.Run("Users", testUsersOne)
}

func TestAll(t *testing.T) {
	t.Run("Headlines", testHeadlinesAll)
	t.Run("Labels", testLabelsAll)
	t.Run("Users", testUsersAll)
}

func TestCount(t *testing.T) {
	t.Run("Headlines", testHeadlinesCount)
	t.Run("Labels", testLabelsCount)
	t.Run("Users", testUsersCount)
}

func TestHooks(t *testing.T) {
	t.Run("Headlines", testHeadlinesHooks)
	t.Run("Labels", testLabelsHooks)
	t.Run("Users", testUsersHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Headlines", testHeadlinesInsert)
	t.Run("Headlines", testHeadlinesInsertWhitelist)
	t.Run("Labels", testLabelsInsert)
	t.Run("Labels", testLabelsInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("LabelToHeadlineUsingHeadline", testLabelToOneHeadlineUsingHeadline)
	t.Run("LabelToUserUsingUser", testLabelToOneUserUsingUser)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("HeadlineToLabels", testHeadlineToManyLabels)
	t.Run("UserToLabels", testUserToManyLabels)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("LabelToHeadlineUsingLabels", testLabelToOneSetOpHeadlineUsingHeadline)
	t.Run("LabelToUserUsingLabels", testLabelToOneSetOpUserUsingUser)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("HeadlineToLabels", testHeadlineToManyAddOpLabels)
	t.Run("UserToLabels", testUserToManyAddOpLabels)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("Headlines", testHeadlinesReload)
	t.Run("Labels", testLabelsReload)
	t.Run("Users", testUsersReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Headlines", testHeadlinesReloadAll)
	t.Run("Labels", testLabelsReloadAll)
	t.Run("Users", testUsersReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Headlines", testHeadlinesSelect)
	t.Run("Labels", testLabelsSelect)
	t.Run("Users", testUsersSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Headlines", testHeadlinesUpdate)
	t.Run("Labels", testLabelsUpdate)
	t.Run("Users", testUsersUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Headlines", testHeadlinesSliceUpdateAll)
	t.Run("Labels", testLabelsSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
}
