// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testClickbaitLabels(t *testing.T) {
	t.Parallel()

	query := ClickbaitLabels()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testClickbaitLabelsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ClickbaitLabel{}
	if err = randomize.Struct(seed, o, clickbaitLabelDBTypes, true, clickbaitLabelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClickbaitLabel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ClickbaitLabels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testClickbaitLabelsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ClickbaitLabel{}
	if err = randomize.Struct(seed, o, clickbaitLabelDBTypes, true, clickbaitLabelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClickbaitLabel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := ClickbaitLabels().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ClickbaitLabels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testClickbaitLabelsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ClickbaitLabel{}
	if err = randomize.Struct(seed, o, clickbaitLabelDBTypes, true, clickbaitLabelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClickbaitLabel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ClickbaitLabelSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ClickbaitLabels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testClickbaitLabelsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ClickbaitLabel{}
	if err = randomize.Struct(seed, o, clickbaitLabelDBTypes, true, clickbaitLabelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClickbaitLabel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ClickbaitLabelExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if ClickbaitLabel exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ClickbaitLabelExists to return true, but got false.")
	}
}

func testClickbaitLabelsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ClickbaitLabel{}
	if err = randomize.Struct(seed, o, clickbaitLabelDBTypes, true, clickbaitLabelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClickbaitLabel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	clickbaitLabelFound, err := FindClickbaitLabel(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if clickbaitLabelFound == nil {
		t.Error("want a record, got nil")
	}
}

func testClickbaitLabelsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ClickbaitLabel{}
	if err = randomize.Struct(seed, o, clickbaitLabelDBTypes, true, clickbaitLabelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClickbaitLabel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = ClickbaitLabels().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testClickbaitLabelsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ClickbaitLabel{}
	if err = randomize.Struct(seed, o, clickbaitLabelDBTypes, true, clickbaitLabelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClickbaitLabel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := ClickbaitLabels().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testClickbaitLabelsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	clickbaitLabelOne := &ClickbaitLabel{}
	clickbaitLabelTwo := &ClickbaitLabel{}
	if err = randomize.Struct(seed, clickbaitLabelOne, clickbaitLabelDBTypes, false, clickbaitLabelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClickbaitLabel struct: %s", err)
	}
	if err = randomize.Struct(seed, clickbaitLabelTwo, clickbaitLabelDBTypes, false, clickbaitLabelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClickbaitLabel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = clickbaitLabelOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = clickbaitLabelTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ClickbaitLabels().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testClickbaitLabelsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	clickbaitLabelOne := &ClickbaitLabel{}
	clickbaitLabelTwo := &ClickbaitLabel{}
	if err = randomize.Struct(seed, clickbaitLabelOne, clickbaitLabelDBTypes, false, clickbaitLabelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClickbaitLabel struct: %s", err)
	}
	if err = randomize.Struct(seed, clickbaitLabelTwo, clickbaitLabelDBTypes, false, clickbaitLabelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClickbaitLabel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = clickbaitLabelOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = clickbaitLabelTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ClickbaitLabels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func clickbaitLabelBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *ClickbaitLabel) error {
	*o = ClickbaitLabel{}
	return nil
}

func clickbaitLabelAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *ClickbaitLabel) error {
	*o = ClickbaitLabel{}
	return nil
}

func clickbaitLabelAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *ClickbaitLabel) error {
	*o = ClickbaitLabel{}
	return nil
}

func clickbaitLabelBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ClickbaitLabel) error {
	*o = ClickbaitLabel{}
	return nil
}

func clickbaitLabelAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ClickbaitLabel) error {
	*o = ClickbaitLabel{}
	return nil
}

func clickbaitLabelBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ClickbaitLabel) error {
	*o = ClickbaitLabel{}
	return nil
}

func clickbaitLabelAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ClickbaitLabel) error {
	*o = ClickbaitLabel{}
	return nil
}

func clickbaitLabelBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ClickbaitLabel) error {
	*o = ClickbaitLabel{}
	return nil
}

func clickbaitLabelAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ClickbaitLabel) error {
	*o = ClickbaitLabel{}
	return nil
}

func testClickbaitLabelsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &ClickbaitLabel{}
	o := &ClickbaitLabel{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, clickbaitLabelDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ClickbaitLabel object: %s", err)
	}

	AddClickbaitLabelHook(boil.BeforeInsertHook, clickbaitLabelBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	clickbaitLabelBeforeInsertHooks = []ClickbaitLabelHook{}

	AddClickbaitLabelHook(boil.AfterInsertHook, clickbaitLabelAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	clickbaitLabelAfterInsertHooks = []ClickbaitLabelHook{}

	AddClickbaitLabelHook(boil.AfterSelectHook, clickbaitLabelAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	clickbaitLabelAfterSelectHooks = []ClickbaitLabelHook{}

	AddClickbaitLabelHook(boil.BeforeUpdateHook, clickbaitLabelBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	clickbaitLabelBeforeUpdateHooks = []ClickbaitLabelHook{}

	AddClickbaitLabelHook(boil.AfterUpdateHook, clickbaitLabelAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	clickbaitLabelAfterUpdateHooks = []ClickbaitLabelHook{}

	AddClickbaitLabelHook(boil.BeforeDeleteHook, clickbaitLabelBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	clickbaitLabelBeforeDeleteHooks = []ClickbaitLabelHook{}

	AddClickbaitLabelHook(boil.AfterDeleteHook, clickbaitLabelAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	clickbaitLabelAfterDeleteHooks = []ClickbaitLabelHook{}

	AddClickbaitLabelHook(boil.BeforeUpsertHook, clickbaitLabelBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	clickbaitLabelBeforeUpsertHooks = []ClickbaitLabelHook{}

	AddClickbaitLabelHook(boil.AfterUpsertHook, clickbaitLabelAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	clickbaitLabelAfterUpsertHooks = []ClickbaitLabelHook{}
}

func testClickbaitLabelsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ClickbaitLabel{}
	if err = randomize.Struct(seed, o, clickbaitLabelDBTypes, true, clickbaitLabelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClickbaitLabel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ClickbaitLabels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testClickbaitLabelsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ClickbaitLabel{}
	if err = randomize.Struct(seed, o, clickbaitLabelDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ClickbaitLabel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(clickbaitLabelColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := ClickbaitLabels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testClickbaitLabelToOneArticleUsingArticle(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local ClickbaitLabel
	var foreign Article

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, clickbaitLabelDBTypes, false, clickbaitLabelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClickbaitLabel struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, articleDBTypes, false, articleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Article struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.ArticleID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Article().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := ClickbaitLabelSlice{&local}
	if err = local.L.LoadArticle(ctx, tx, false, (*[]*ClickbaitLabel)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Article == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Article = nil
	if err = local.L.LoadArticle(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Article == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testClickbaitLabelToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local ClickbaitLabel
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, clickbaitLabelDBTypes, false, clickbaitLabelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClickbaitLabel struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := ClickbaitLabelSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*ClickbaitLabel)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testClickbaitLabelToOneSetOpArticleUsingArticle(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ClickbaitLabel
	var b, c Article

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, clickbaitLabelDBTypes, false, strmangle.SetComplement(clickbaitLabelPrimaryKeyColumns, clickbaitLabelColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, articleDBTypes, false, strmangle.SetComplement(articlePrimaryKeyColumns, articleColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, articleDBTypes, false, strmangle.SetComplement(articlePrimaryKeyColumns, articleColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Article{&b, &c} {
		err = a.SetArticle(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Article != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.ClickbaitLabels[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.ArticleID != x.ID {
			t.Error("foreign key was wrong value", a.ArticleID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.ArticleID))
		reflect.Indirect(reflect.ValueOf(&a.ArticleID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.ArticleID != x.ID {
			t.Error("foreign key was wrong value", a.ArticleID, x.ID)
		}
	}
}
func testClickbaitLabelToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ClickbaitLabel
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, clickbaitLabelDBTypes, false, strmangle.SetComplement(clickbaitLabelPrimaryKeyColumns, clickbaitLabelColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.ClickbaitLabels[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testClickbaitLabelsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ClickbaitLabel{}
	if err = randomize.Struct(seed, o, clickbaitLabelDBTypes, true, clickbaitLabelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClickbaitLabel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testClickbaitLabelsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ClickbaitLabel{}
	if err = randomize.Struct(seed, o, clickbaitLabelDBTypes, true, clickbaitLabelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClickbaitLabel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ClickbaitLabelSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testClickbaitLabelsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ClickbaitLabel{}
	if err = randomize.Struct(seed, o, clickbaitLabelDBTypes, true, clickbaitLabelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClickbaitLabel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ClickbaitLabels().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	clickbaitLabelDBTypes = map[string]string{`ID`: `character varying`, `UserID`: `character varying`, `ArticleID`: `character varying`, `Value`: `character varying`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_                     = bytes.MinRead
)

func testClickbaitLabelsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(clickbaitLabelPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(clickbaitLabelAllColumns) == len(clickbaitLabelPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ClickbaitLabel{}
	if err = randomize.Struct(seed, o, clickbaitLabelDBTypes, true, clickbaitLabelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClickbaitLabel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ClickbaitLabels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, clickbaitLabelDBTypes, true, clickbaitLabelPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ClickbaitLabel struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testClickbaitLabelsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(clickbaitLabelAllColumns) == len(clickbaitLabelPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ClickbaitLabel{}
	if err = randomize.Struct(seed, o, clickbaitLabelDBTypes, true, clickbaitLabelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClickbaitLabel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ClickbaitLabels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, clickbaitLabelDBTypes, true, clickbaitLabelPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ClickbaitLabel struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(clickbaitLabelAllColumns, clickbaitLabelPrimaryKeyColumns) {
		fields = clickbaitLabelAllColumns
	} else {
		fields = strmangle.SetComplement(
			clickbaitLabelAllColumns,
			clickbaitLabelPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ClickbaitLabelSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testClickbaitLabelsUpsert(t *testing.T) {
	t.Parallel()

	if len(clickbaitLabelAllColumns) == len(clickbaitLabelPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := ClickbaitLabel{}
	if err = randomize.Struct(seed, &o, clickbaitLabelDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ClickbaitLabel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ClickbaitLabel: %s", err)
	}

	count, err := ClickbaitLabels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, clickbaitLabelDBTypes, false, clickbaitLabelPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ClickbaitLabel struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ClickbaitLabel: %s", err)
	}

	count, err = ClickbaitLabels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
